In [1]:
import pandas as pd

In [2]:
import os
import glob

csv_files = glob.glob('./*.csv')

# 각 파일을 반복하며 읽어와 하나의 데이터프레임으로 합칩니다.
all_data = pd.DataFrame()
for f in csv_files:
    try:
        df = pd.read_csv(f, encoding='utf-8')
    except UnicodeDecodeError:
        # If cp949 fails, try euc-kr:
        try:
            df = pd.read_csv(f, encoding='cp949')
        except UnicodeDecodeError:
            # As a last resort, try 'latin1' (though data might look wrong if it's Korean)
            df = pd.read_csv(f, encoding='latin1')

all_data = pd.concat([all_data, df], ignore_index=True)

In [3]:
all_data.head(7)

,SIGUNGU_CD,EMDL_CD,CLL,HMNO,VCNO,ADRES_NM,HOUSE_TYPE,HSMP_NM,BILDNG_YR,FLR,XUAR,CNTRCT_YM,CNTCT_DE,TRNS_CLSF,TRAMT,ASSRNC_AMT,MTHT_AMT,NRB_SWST_NM,NRB_SWST_DIST
0,11110,10500,1,98,2,서울특별시 종로구 창성동 98-2,연립다세대,이본팔레스,2000.0,2,75.27,202503,19,매매,57000,0,0,경복궁(정부서울청사)역,483
1,11110,11300,1,27,1,서울특별시 종로구 필운동 27-1,연립다세대,양지빌라,2001.0,4,84.72,202503,1,매매,62800,0,0,경복궁(정부서울청사)역,492
2,11110,11300,1,97,0,서울특별시 종로구 필운동 97,연립다세대,(97-0),2003.0,5,109.04,202503,18,전세,0,64000,0,경복궁(정부서울청사)역,296
3,11110,11300,1,174,1,서울특별시 종로구 필운동 174-1,아파트,두레엘리시안,2007.0,7,59.85,202503,25,매매,89000,0,0,경복궁(정부서울청사)역,289
4,11110,11300,1,254,0,서울특별시 종로구 필운동 254,아파트,신동아블루아광화문의꿈,2007.0,7,111.97,202503,31,전세,0,97000,0,경복궁(정부서울청사)역,177
5,11110,11300,1,285,5,서울특별시 종로구 필운동 285-5,오피스텔,파크뷰타워,1998.0,8,25.65,202503,5,월세,0,2000,70,경복궁(정부서울청사)역,225
6,11110,11500,1,9,0,서울특별시 종로구 사직동 9,아파트,광화문스페이스본(101동~105동),2008.0,4,136.40,202503,18,매매,199000,0,0,경복궁(정부서울청사)역,236

In [4]:
all_data.shape

(59144, 19)

In [5]:
all_data.isnull().sum()

SIGUNGU_CD         0
EMDL_CD            0
CLL                0
HMNO               0
VCNO               0
ADRES_NM           0
HOUSE_TYPE         0
HSMP_NM            0
BILDNG_YR        159
FLR                0
XUAR               0
CNTRCT_YM          0
CNTCT_DE           0
TRNS_CLSF          0
TRAMT              0
ASSRNC_AMT         0
MTHT_AMT           0
NRB_SWST_NM        0
NRB_SWST_DIST      0
dtype: int64

In [ ]:
## 역 이름 뒤에 -역 제외하기
station_name=[]

for i in all_data['NRB_SWST_NM']:
    if '역' not in i:
        station_name.append(i)
    else:
        if i[-1] == '역':
            station_name.append(i[:-1])
            continue
        if '(' in i:
            if '호선' in i:
                station_name.append(i.split('(')[0][:-1])
                continue
            else:
                if i.split('(')[0][-1] == '역':
                    station_name.append(i.split('(')[0][:-1]+'('+i.split('(')[1][:])
                    continue
                elif len(i.split(')')[1])>0 and i.split(')')[1][0] == '역':
                    station_name.append(i.split(')')[0][:]+')')
                    continue
        if ' ' in i:
            if i.split(' ')[0][-1] == '역':
                station_name.append(i.split(' ')[0][:-1]+i.split(' ')[1][:])
                continue
        else:
            station_name.append(i)

print(len(station_name))
print(all_data.shape)

59144
(59144, 19)

In [7]:
all_data['NRB_SWST_NM']=station_name

In [8]:
all_data

,SIGUNGU_CD,EMDL_CD,CLL,HMNO,VCNO,ADRES_NM,HOUSE_TYPE,HSMP_NM,BILDNG_YR,FLR,XUAR,CNTRCT_YM,CNTCT_DE,TRNS_CLSF,TRAMT,ASSRNC_AMT,MTHT_AMT,NRB_SWST_NM,NRB_SWST_DIST
0,11110,10500,1,98,2,서울특별시 종로구 창성동 98-2,연립다세대,이본팔레스,2000.0,2,75.27,202503,19,매매,57000,0,0,경복궁(정부서울청사),483
1,11110,11300,1,27,1,서울특별시 종로구 필운동 27-1,연립다세대,양지빌라,2001.0,4,84.72,202503,1,매매,62800,0,0,경복궁(정부서울청사),492
2,11110,11300,1,97,0,서울특별시 종로구 필운동 97,연립다세대,(97-0),2003.0,5,109.04,202503,18,전세,0,64000,0,경복궁(정부서울청사),296
3,11110,11300,1,174,1,서울특별시 종로구 필운동 174-1,아파트,두레엘리시안,2007.0,7,59.85,202503,25,매매,89000,0,0,경복궁(정부서울청사),289
4,11110,11300,1,254,0,서울특별시 종로구 필운동 254,아파트,신동아블루아광화문의꿈,2007.0,7,111.97,202503,31,전세,0,97000,0,경복궁(정부서울청사),177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59139,41830,40024,1,1052,0,경기도 양평군 용문면 다문리 1052,아파트,용문코아루,2016.0,18,62.74,202503,17,월세,0,2000,80,용문,495
59140,41830,40024,1,1107,0,경기도 양평군 용문면 다문리 1107,아파트,용문역반도유보라아이비파크,2023.0,7,59.99,202503,25,매매,29700,0,0,용문,145
59141,41830,40024,1,1107,0,경기도 양평군 용문면 다문리 1107,아파트,용문역반도유보라아이비파크,2023.0,9,84.97,202503,6,매매,38700,0,0,용문,145
59142,41830,40024,1,1107,0,경기도 양평군 용문면 다문리 1107,아파트,용문역반도유보라아이비파크,2023.0,4,59.99,202503,20,월세,0,2000,80,용문,145
59143,41830,40024,1,1107,0,경기도 양평군 용문면 다문리 1107,아파트,용문역반도유보라아이비파크,2023.0,12,60.00,202503,17,전세,0,22000,0,용문,145

In [9]:
all_data.drop(columns=['SIGUNGU_CD','EMDL_CD','ADRES_NM','HSMP_NM', 'XUAR', 'FLR', 'BILDNG_YR', 'VCNO', 'HMNO', 'CLL'], inplace=True)

In [10]:
all_data.tail()

,HOUSE_TYPE,CNTRCT_YM,CNTCT_DE,TRNS_CLSF,TRAMT,ASSRNC_AMT,MTHT_AMT,NRB_SWST_NM,NRB_SWST_DIST
59139,아파트,202503,17,월세,0,2000,80,용문,495
59140,아파트,202503,25,매매,29700,0,0,용문,145
59141,아파트,202503,6,매매,38700,0,0,용문,145
59142,아파트,202503,20,월세,0,2000,80,용문,145
59143,아파트,202503,17,전세,0,22000,0,용문,145

In [12]:
all_data.to_csv('house_price.csv',encoding='cp949', index=True)

In [ ]:
print(len(station_name))

58888